---
name: Semantic Release Action
description: Creates a new release using Semantic Versioning.
author: Mircea-Pavel Anton

inputs:
  dry-run:
    description: "Perform a dry run without creating an actual release"
    required: false
    default: "false"
  github-token:
    description: "GitHub token with repository access"
    required: true
  version-increment:
    description: "Version increment strategy (major, minor, patch, prerelease or auto)"
    required: false
    default: "auto"

runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5
      with:
        go-version: "stable"

    - name: Install SVU
      shell: bash
      run: go install github.com/caarlos0/svu/v3@v3.2.3

    - name: Release
      uses: actions/github-script@v7.0.1
      env:
        DRY_RUN: ${{ inputs.dry-run }}
        VERSION_INCREMENT: ${{ inputs.version-increment }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        script: |
          const path = require('path');
          const scriptPath = path.join(process.env.GITHUB_ACTION_PATH, 'src/release.js');
          
          // Use dynamic import to load the script
          const { main } = require(scriptPath);
          
          // Run the main function
          await main();
